[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trend-following-research"
version = "0.1.0"
description = "Backtesting trend-following algorithms"
requires-python = ">=3.11"
dependencies = [
  "pandas",
  "yfinance",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
